services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: inception-mariadb
    env_file: ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
volumes:
  mariadb_data:
    driver_opts:
      type: none
      device: /home/maxime/data/mariadb
      o: bind
  wordpress_files:
    driver_opts:
      type: none
      device: /home/maxime/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge
